### ISSUE TITLE
whatsapp: false positive http://web.whatsapp.com/ measurement results

### ISSUE THREAD

**Issue by bassosimone** [ooni/ooni.org#1317]
As of 2022-12-02, the [`whatsapp` nettest](https://github.com/ooni/spec/blob/9248b94f911cb1687d8c07a973ed8adedfa08253/nettests/ts-018-whatsapp.md) tests [WhatsApp Web](https://web.whatsapp.com/) by checking for (a) http://web.whatsapp.com and (b) https://web.whatsapp.com in parallel. The [nettest implementation](https://github.com/ooni/probe-cli/blob/v3.16.6/internal/engine/experiment/whatsapp/whatsapp.go#L103) says that WhatsApp Web is accessible if we get a "302 Found" redirect for (a) and we can successfully create an HTTPS connection for (b).

Today our colleague @sloncocs noticed that http://web.whatsapp.com (i.e., URL (a) above) stopped responding with 302 when interrogated by OONI Probe and (for what is worth) by other command line tools. Rather, the response we get is now "403 Forbidden". We do not know the exact reason why this happening as we are still investigating the matter.

However, this change is relevant to the automatic determination of WhatsApp Web blocking made by OONI Probe. It is safe to assume that, in most if not all cases, results indicating WhatsApp Web blocking are a false positive caused by what looks like a change in the behavior in WhatsApp servers (which obviously are not under our control).

We will start mitigating this issue by implementing a fix in our data processing pipeline, which will stop taking into account URL (a) for determining whether WhatsApp web is blocked. You can read the proposed change at [pipeline#403](https://github.com/ooni/pipeline/pull/403). Once this change will land in production, WhatsApp measurements would not show signs of this false positive when accessed through OONI Explorer.

Yet, of course, the fix for this false positive would not be complete until we fix the matter in OONI Probe. To fix this issue we are planning on attacking the problem from two sides. On the one end, we are planning on dropping measuring the HTTP URL, indicated as (a) above, from the experiment implementation. On the other end, we will reflect how, in the medium term we can more flexibly handle server-side changes outside of our control such as the one at hand without making a new probe release.

More in detail, this is a list of the next steps to address this issue:

- [x] https://github.com/ooni/pipeline/pull/403
- [x] deploy https://github.com/ooni/pipeline/pull/403 to prod [done at 5 PM Rome time]
- [x] https://github.com/ooni/probe/issues/2374
- [x] https://github.com/ooni/probe/issues/2382
- [x] https://github.com/ooni/probe/issues/2383
- [x] https://github.com/ooni/probe/issues/2384
- [x] https://github.com/ooni/probe/issues/2375
- [x] published new debian packages
- [x] https://github.com/ooni/probe/issues/2376
- [x] https://github.com/ooni/probe/issues/2377
- [ ] understand the underlying reason why this happens
- [ ] see whether we can solve this problem with OONI Run v2 descriptors
- [ ] see whether we can disable tests using the check-in API
- [ ] see whether we can provide the definition of tests to probes dynamically
