### ISSUE TITLE
Autodetection - PoC of observation analysis creating experiment results

### ISSUE THREAD

**Issue by jbonisteel** [ooni/ooni.org#1449]
This is about implement a PoC of the experiment result generation which implements the Likelyhood of Network Interference (LoNI) confidence metric.

The goal of this metric is to estimate for a given interval of time and location how likely some form of restriction is affecting a particular target.

As part of this PoC we will also include a minimal HTTP API to retrieve the data, display it and interpret it.

Here is the estimate breakdown of the tasks required for doing this:
* [x] Implement LoNI metrics at the observation level
* [x] Implement LoNI metrics at the measurement level
* [x] Implement metrics which go from granular to high level
* [ ] Formalize and document the metric and explain how it works
* [x] Collect feedback from researchers on this metric

Potentially this metric could also be an important building block in improving the censorship alert system.

**Comment by hellais** [comment]
I am still missing a bit more work on formalizing the metric and explaining how it works.

I have updated some of the design docs however here: https://github.com/ooni/data/pull/81. I think in general more research is needed to fully formalize the LoNI metric so I am going to close this epic and defer that to future work.
