### ISSUE TITLE
Autodetection - setup system for validating the experiment results

### ISSUE THREAD

**Issue by jbonisteel** [ooni/ooni.org#1450]
This is about setting up a system that allows us to estimate how accurate our loni metric is and what it's key evaluation metrics are.

As part of this activity the following tasks are needed:
* [ ] Research what can be used as a ground truth
* [ ] Build a ground truth to compare the analysis against
* [ ] Implement the ground truth to analysis comparison system
* [ ] Run the comparison and evaluate the performance of the model

This work is highly iterative and feeds directly back into the improvement of the analysis and is a precursor to completing the PoC of the analysis. It is however also very instrumental to getting this into production so it will continue going forward (especially the last 2 points about running it and improving the comparison system)
