### ISSUE TITLE
Add support for Richer Input in OONI Run v2 backend

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#1647]
We would like to add support for returning richer input specifications inside of OONI Run v2 descriptors.

This has the nice benefit that we would not have to pass through a dedicated API endpoint and we can potentially also make use of the caching which happens by default in in-app descriptor loading.

As part of this epic we should:
* [x] Collect some of the requirements for richer input (started in the [engine simplification doc](https://docs.google.com/document/d/1CDYNleCcz9uywsuo8k0U1W46SuJQFLvpl9jYU1VJaR8/edit?tab=t.0#heading=h.zf52ea9zkstk))
* [x] Come up with a new revision of the spec
* [x] Implement it in the backend
* [ ] Implement support for it in the engine

**Comment by hellais** [comment]
This has been done here: https://github.com/ooni/backend/pull/962
