### ISSUE TITLE
Collect community feedback and research the limitations to the current OONI Run link format

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#345]
We will conduct an OONI Run usability study with community members to explore the limitations to the current OONI Run link format and collect community feedback for improvement. 

Based on past community feedback, the known main challenges that OONI Run users are facing are the following:

Issues related to sharing OONI Run links due to their length;
Issues related to triggering the mobile app deep link and opening the OONI Probe mobile app;
Issues related to OONI Run links breaking or getting mangled by specific messaging clients.

To address these issues, we plan to collect further community feedback in order to work on the following areas:

We will assess the list of platforms used to share OONI Run links (such as Twitter, WhatsApp, email, etc.). Each of these platforms presents unique challenges and breaks OONI Run links in different ways. 
We will define a process to ensure that the solutions we develop for fixing OONI Run links work reliably on the target platforms.
We will work on reducing the overall length of OONI Run links by using compression and changing the encoding system to be more robust to mangling by apps.
We will evaluate the possibility of either developing a URL shortener ourselves, or testing and adding support for using third-party URL shorteners with OONI Run links.

**Comment by agrabeli** [comment]
As part of this activity, I will:

- [ ] Create a survey to share with community members

- [ ] Draft interview questions for a usability study

- [ ] Interview community members to collect their feedback

**Comment by hellais** [comment]
@agrabeli has completed writing a report based on the interviews and survey. This will be published soon.

This activity is done.

**Comment by agrabeli** [comment]
The report has been published: https://ooni.org/post/2020-06-09-ooni-run-usability-study-findings/

**Comment by hellais** [comment]
This has been completed, we should migrate the issues outside of the epic and close it.

**Comment by hellais** [comment]
I have moved all the issues to the improve upon OONI Run epic. I am going to close this epic as done!
