### ISSUE TITLE
Internews Internet Measurement training online workshop

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#598]
OONI got a grant from internews for 7k to work on recording and leading a series of webinars on internet measurement.

This epic is to track the work we should do for it.

Timeline of this is:
* [x] Share with internews a draft SoW and contract template for them to review and embed in their standard contract template (done on July 20th)
* [x] Share outline of the sessions with Internews (done by August 21st)
* [x] Receive contract for Internew for the work to do (received on August 27th)
* [x] Finalise Hermes admin review of the contract
* [x] Send to internews signed contract (Sept 1st)
* [x] Review the existing videos to understand how to "align them stylistically" OR get response from internews on the necessary changes that need to be done to the streamyard template
* [x] Research, prepare and record the Introduction to network measurement session (@hellais): https://github.com/ooni/ooni.org/issues/595
* [x] Record OONI webinar session (@agrabeli): https://github.com/ooni/ooni.org/issues/586 (Sept 1st)

We will update this epic as new TODO items appear

**Comment by hellais** [comment]
Internews requests us today that we use the powerpoint software to record the sessions. As I do not have this software installed on my machine and we had already agreed we would be using our paid streamyard platform for the recording.

My ask to them is what does powerpoint do that we cannot do using our platform. That way we can maybe do some changes to our streamyard template in order to better fit with the vision they had for the project.

I am putting this project on hold until further clarifications.

The deadline of the end of next week might have to be adjust as a result of these changes in the requirements.

**Comment by hellais** [comment]
As an update internews requested I review the existing videos to "align them stylistically". As a result of these updated requirements I am going to have to de-prioritise and move this over to the next sprint.

**Comment by bassosimone** [comment]
(@agrabeli AFAICT this should be in Sprint 22, so perhaps we should assign it to the sprint and move to Sprint Backlog?)

**Comment by agrabeli** [comment]
I have completed this all.
