### ISSUE TITLE
Create epics from activities of the DRL grant

### ISSUE THREAD

**Issue by hellais** [ooni/ooni.org#638]
This is about integrating the following points into our roadmap and migrating issues from the OTF grant into the DRL one.

These are the 3 objectives and the activities part of them:

**Objective 1: Expand the breadth and granularity of coverage of global censorship events**
* [x] 1.1 Expand censorship measurement methodologies through the creation of new OONI Probe tests: https://github.com/ooni/ooni.org/issues/639
* [x] 1.2 Improve OONI Probe mobile and desktop apps: https://github.com/ooni/ooni.org/issues/342
* [x] 1.3 Add support to OONI Probe Android app for daily collection of measurements from stable vantage points: https://github.com/ooni/ooni.org/issues/640
* [x] 1.4 Improve OONI backend infrastructure: https://github.com/ooni/ooni.org/issues/641

**Objective 2: Promote rapid response to emergent global censorship events**
* [x] 2.1 Create a real-time incident response dashboard: https://github.com/ooni/ooni.org/issues/642
* [x] 2.2 Improve Probe Orchestration system to dynamically schedule and orchestrate OONI Probe tests: https://github.com/ooni/ooni.org/issues/643
* [x] 2.3 Create a browser-based web censorship measurement tool: https://github.com/ooni/ooni.org/issues/644
* [x] 2.4 Improve upon OONI Explorer: https://github.com/ooni/ooni.org/issues/645
* [x] 2.5 Create a smart URL list system: https://github.com/ooni/ooni.org/issues/646

**Objective 3: Empower community participation in censorship measurement research**
* [x] 3.1 Create platform to enable community contributions to test lists: https://github.com/ooni/ooni.org/issues/647
* [x] 3.2 Create resources to support community engagement activities: https://github.com/ooni/ooni.org/issues/648
* [x] 3.3 Facilitate censorship measurement workshops: https://github.com/ooni/ooni.org/issues/649

**Comment by hellais** [comment]
Unassigning myself and assigning @agrabeli to validate that everything is OK and if so close the issue.

**Comment by hellais** [comment]
I have dropped the funder/otf label from all the issues that now belong in funder/drl20 and moved the issues inside of the relevant epic.

I think we can consider this done.
