### ISSUE TITLE
Create tickets and detailed timeline based on DISRUPT milestones + activities workplan

### ISSUE THREAD

**Issue by agrabeli** [ooni/ooni.org#749]
Starting from 1st February 2021, we'll start working on the DISRUPT project to measure pluggable transports (for 12 months). We have already created a detailed (internal) timeline for the activities, but they need to be tracked on Github.

Specifically, we need to:

- [x] Create epics based on the milestones
- [x] Create tickets for each epic/milestone
- [x] Allocate epics in pre-determined timeline
- [x] Determine start dates for all tickets

**Comment by hellais** [comment]
This is done. I have created and flagged all issues related to the DISRUPT project with the label funder/internews21.

They have all been added to our roadmap:
![Screenshot 2021-01-20 at 13.26.47.png](https://images.zenhubusercontent.com/58442543b9dc3c622022e97d/ec342bf9-e177-4da6-a72e-592e33448eab)
